/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovS1VMSUFIL1BlbXJvZ3JhbWFuIFdlYiBMYW5qdXQvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC8xMi5EZXBsb3ltZW50L3NyYy9hcHAvYWRtaW4vYWRtaW4uY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9LVUxJQUgvUGVtcm9ncmFtYW4gV2ViIExhbmp1dC9QZW1yb2dyYW1hbi1XZWItTGFuanV0LzEyLkRlcGxveW1lbnQvc3JjL2FwcC9hZG1pbi9hZG1pbi5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
