/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovS1VMSUFIL1BlbXJvZ3JhbWFuIFdlYiBMYW5qdXQvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC8xMi5EZXBsb3ltZW50L3NyYy9hcHAvaG9tZS9ob21lLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovS1VMSUFIL1BlbXJvZ3JhbWFuIFdlYiBMYW5qdXQvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC8xMi5EZXBsb3ltZW50L3NyYy9hcHAvaG9tZS9ob21lLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
