/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovS1VMSUFIL1BlbXJvZ3JhbWFuIFdlYiBMYW5qdXQvUGVtcm9ncmFtYW4tV2ViLUxhbmp1dC8xMi5EZXBsb3ltZW50L3NyYy9hcHAvbm90LWZvdW5kL25vdC1mb3VuZC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0tVTElBSC9QZW1yb2dyYW1hbiBXZWIgTGFuanV0L1BlbXJvZ3JhbWFuLVdlYi1MYW5qdXQvMTIuRGVwbG95bWVudC9zcmMvYXBwL25vdC1mb3VuZC9ub3QtZm91bmQuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
